Prod
decentramall/decentramall-backend pull request #1
Opened 2020-09-21 09:27 UTC by easonchai

2020-09-21 09:28 UTC, easonchai commented
Still got loads to add, but got the structure working

2020-09-21 22:59 UTC, obernardovieira commented
It's important to remember what we are saving.
We only want an API as of now, because it isn't reliable yet (nor we have experience) to support an orbitdb instance. For that reason, we will use a postgres and so we need the api.

So, we are saving this https://github.com/decentramall/decentramall-ui/blob/master/src/storage/index.ts#L11
Instead of publishing to filecoin right away, we should first upload the picture storefront to AWS (I can provide the credentials to some space) and save its URL and the metadata to postgres.

So, I don't agree in having the *space* model. The *store* one is good, but I see you've put *store_image* as BLOB, so I'm assuming you are thinking of saving the image there. Nah, please don't. It will increase a lot the db size and it's not the SQL goal.

So I'll leave just the store model, just the store route.

But you are going good :clap: . I'm happy to setup an heroku instance with a postgres database if you want.

2020-09-21 22:59 UTC, obernardovieira requested changes
It's important to remember what we are saving.
We only want an API as of now, because it isn't reliable yet (nor we have experience) to support an orbitdb instance. For that reason, we will use a postgres and so we need the api.

So, we are saving this https://github.com/decentramall/decentramall-ui/blob/master/src/storage/index.ts#L11
Instead of publishing to filecoin right away, we should first upload the picture storefront to AWS (I can provide the credentials to some space) and save its URL and the metadata to postgres.

So, I don't agree in having the *space* model. The *store* one is good, but I see you've put *store_image* as BLOB, so I'm assuming you are thinking of saving the image there. Nah, please don't. It will increase a lot the db size and it's not the SQL goal.

So I'll leave just the store model, just the store route.

But you are going good :clap: . I'm happy to setup an heroku instance with a postgres database if you want.

2020-09-22 08:30 UTC, miguelemos approved these changes

2020-09-22 22:22 UTC, closed without merging